# name: Daily cron job
# on:
#   schedule:
#     - cron: '*/5 * * * *' # this will run every 10 minutes
# jobs:
#   cron:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Daily cron job
#         run: |
#           curl --request POST \
#           --url 'https://akesis.proterrasancta.org/api/forgotten-donations/remind/' \
#           --header 'Authorization: Bearer ${{ secrets.CRON_KEY }}'
